FROM python:3.8

WORKDIR /parser

RUN mkdir /etc/parser_2/

ADD secrets.yaml /etc/parser_2/secrets.yaml

ADD /requirements.txt ./requirements.txt

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

ADD . .

CMD ["python3", "parser.py"]